### PR TITLE
Added 'priceMicros' field for Product on iOS

### PR DESCRIPTION
**Pull request by kurtsergey**
Added numeric field in order to pass directly to analytics

### CODE REVIEW

**Comment by j3k0** [comment]
Thanks @kurtsergey 

I've read through your PR.

There's 1 small mistake and 1 point I'd like to discuss :

First, as stated on top of the file, changes to `api.md` will be lost as it's a file generated from comments in the source-code. The description of the the `countryCode` and `priceValue` fields should be in one of the javascript files (`product.js` I believe). `api.md` will be generated with `make doc`

Secondly, `priceValue` is basically a duplicate of `priceMicros` (with a different multiplier). Since it doesn't make a lot of sense to provide both in the API, maybe a better solution would be to just bring `priceMicros` to iOS. (then it stays backward compatible for people already using it on Android, and we can remove the warning that it exists _only on Android_)

**Comment by kurtsergey** [comment]
@j3k0 thanks for review.
I've fixed documentation.
I'm not sure about `priceValue` / `priceMicros`. Every user of plugin must multiply `priceMicros` by 1000000. Maybe `priceMicros` should be marked as deprecated.
So we need your solution about `priceValue` field :)

**Comment by kurtsergey** [comment]
@j3k0 So what do you think?

**Comment by j3k0** [comment]
@kurtsergey Sorry, I seem to have missed the notification for your comment.

I'd stick with `priceMicros` everywhere (iOS and Android) for three reasons:

 - I value backward compatibility and API stability a lot. People don't like when their app breaks after updating a plugin.
 - For some reasons, Google did choose to have only `priceMicros` in their API. Seems to work fine for Android.
 - In years, we didn't have any complain to have to multiply `priceMicros` by `1000000`, so there's no reason to fix something that isn't a problem.

Sorry again for the delay.

**Comment by kurtsergey** [comment]
OK, I will remove `priceValue` field and keep `priceMicros` only.

**Comment by j3k0** [comment]
I get the following build errors:

```
/tmp/build-4296/platforms/ios/Test/Plugins/cc.fovea.cordova.purchase/InAppPurchase.m:852:39:error:invalid operands to binary expression ('NSDecimalNumber *' and 'int')
                NILABLE(product.price * 1000000),      @"priceMicros"
                        ~~~~~~~~~~~~~ ^ ~~~~~~~
/tmp/build-4296/platforms/ios/Test/Plugins/cc.fovea.cordova.purchase/InAppPurchase.m:23:24:note:expanded from macro 'NILABLE'
#define NILABLE(obj) ((obj) != nil ? (NSObject *)(obj) : (NSObject *)[NSNull null])
                       ^~~
/tmp/build-4296/platforms/ios/Test/Plugins/cc.fovea.cordova.purchase/InAppPurchase.m:852:39:error:invalid operands to binary expression ('NSDecimalNumber *' and 'int')
                NILABLE(product.price * 1000000),      @"priceMicros"
                        ~~~~~~~~~~~~~ ^ ~~~~~~~
```

**Comment by kurtsergey** [comment]
@j3k0 Thank you for review and sorry for build issue. I fixed it by your recommendation, please review again.

**Comment by j3k0** [comment]
Thanks for the contribution.

Seing than Apple uses this special class `NSDecimalNumber` to represent prices. I understand better the value of using an integer value like `priceMicros` instead of a floating point like `price`.

A floating point value might be rounded to something slightly off, since floating points use power-of-two instead of power-of-ten to represent numbers. Rounding errors are not something you want when charging people money.

**Comment by kurtsergey** [comment]
@j3k0 Do you have plan to publish release?

**Comment by j3k0** [comment]
I will, but generally I prefer to let new features sit for a week or two before releasing. This to give time to give some people installing the plugin from the git repo to test and complain if anything breaks.

You can use the plugin with `cordova plugin add https://github.com/j3k0/cordova-plugin-purchase.git` until then.

**Pull request merged**
