### PR TITLE
Added ability in android to upgrade an existing user subscription

### PR DESCRIPTION
**Pull request by souly1**
Accorrding to android API:
[android developer](https://developer.android.com/google/play/billing/billing_reference.html#upgrade-getBuyIntentToReplaceSkus)

Tested for production in our App

### CODE REVIEW

**Comment by j3k0** [comment]
Thanks, it seems all good. I'm trusting you that it works (or I trust people using git instead of a stable release to complain).

Little note: `doc/api.md` shouldn't have been edited manually, since it's generated from source code. Moved your changed to `src/js/order.js`

**Comment by souly1** [comment]
Cool, thanks @j3k0 , I'm sure the community will enjoy the update and help with finding and fixing any issues, should they arise.

**Comment by jonathankau** [comment]
@souly1 For some reason, when trying to trigger an upgrade, the new subscription gets purchased, but the old one is not getting canceled/replaced.

Here's how we attempt to trigger the upgrade:
```js
  window.store.order(productID, oldProductID ? { oldPurchasedSkus: [ oldProductID ] } : null);
```

I've verified that `oldProductID` is a valid string representing the old subscription type. Any ideas on how we may be using this functionality incorrectly?

**Comment by jonathankau** [comment]
EDIT: Looks like we were still on 6.0.0, which didn't include the upgrade code 😓 .

**Comment by Defcon0** [comment]
AWESOME! I'll check it right away since I needed this feature desperately, too. Still wondering what other app developers using this plugin might have been doing without this feature. Making sure that only one subscription is active at once manually is very hard if not impossible since the user can cancel a subscription but it runs til the end of the subscription period anyway. After this period the user would have to make a new subscription. What a rediculous solution.

Anyway, I'll check in no time the new feature!

**Comment by Almerick** [comment]
Is the upgrade/downgrade functionality between subscription groups available at all on the iOS platform?

**Pull request merged**
