### PR TITLE
Make compatible with cordova-ios 4

### PR DESCRIPTION
**Pull request by hypery2k**
use built-in base64 methods, see #358

### CODE REVIEW

**Comment by j3k0** [comment]
Thanks. Any idea if that would prevent the plugin to compile with older Cordova versions? Maybe we should add some `#ifdef`?

**Comment by hypery2k** [comment]
good point, but then we should first wrap the base64 method into an helper method and wrap a #ifdef around the import and the helper method logic

**Comment by j3k0** [comment]
@hypery2k If you know how to make this right, that would be super nice. I think merging this in would be a must, but there are still Cordova 3 users out there.

**Comment by j3k0** [comment]
Maybe this would work: https://github.com/j3k0/cordova-plugin-purchase/pull/362 ?

(Just found it out in GitHub's "Network", those guys didn't submit a PR for that fix).

**Comment by hypery2k** [comment]
Not sure if this one will work for Cordova 3 and 4 but I can take a look

**Pull request closed without merging**
