### PR TITLE
fix crash when logged out of icloud

### PR DESCRIPTION
**Pull request by kasparsj**
tested on ios 16 / iphone8

Changes proposed in this pull request:

- fix crash when logged out of icloud

---

To test this pull request with cordova:

```
# 1: Uninstall the plugin (if already installed)
cordova plugin rm cordova-plugin-purchase

# 2: Install from github
cordova plugin add "https://github.com/j3k0/cordova-plugin-purchase.git#BRANCH_NAME_HERE"
```

### CODE REVIEW

**Comment by j3k0** [comment]
Thanks, didn't know Cordova could pass in `NsNull.null`. Not sure how this is related with iCloud, as `store.applicationUsername` is a value provided by the app. Maybe you are using iCloud to store and load the `applicationUsername`? Anyway, the fix can prevent bugs.

**Comment by nathanielop** [comment]
@j3k0 Is this cut into a new version yet (>13.1.4)? Hitting this issue when testing on latest seems

**Comment by j3k0** [comment]
Fix not publish yet, but available from `master` branch if you want to install from git repo.

**Comment by nathanielop** [comment]
Sounds good for the moment. Thanks for the prompt response.

**Pull request closed without merging**
