### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by dkarzon**
Continuing on from #229 I have merged the majority of the bridge and adapter code into a single one.

### CODE REVIEW

**Comment by dkarzon** [comment]
@j3k0 How do I go about building it? Running the build target from the makefile references files in a git_modules folder that doesn't exist.

This is currently untested.

**Comment by j3k0** [comment]
Hey, you should first make sure that `make test-js` doesn't fail.

The linter finds trailing whitespace... no big deal but that fails the build.

Then, the Makefile used to pull and synchronize Android code from a git submodule. It's not the case anymore, the "git_modules" thingy is commented out and unnecessary.

To test it, you can use the demo project https://github.com/Fovea/cordova-plugin-purchase-demo enable windows platform, install the plugin from git with `cordova plugin add <git repo url>` and launch. You should see the plugin trying to initialize on the console.

Do not hesitate if you need any more help.

**Comment by dkarzon** [comment]
Why is whitespace a problem?
This is the error I get when trying to run the `make build` command: 
image

**Comment by dkarzon** [comment]
@j3k0 I couldn't get your makefile running on windows, first problem was path separators, then it kept trying the run the `sync-android` part even though it was commented out. Then piping to uglifyjs wouldn't work so in the end I just ran the process script manually to generate the files. (As stated in docs/windows.md)

Also added some docs on setting up testing on windows.

This now conflicts with master because I changed `www/store-android.js` but I don't think it really changed that much (apart from skipping the `uglifyjs -b` step)

**Comment by j3k0** [comment]
Hi Damian, great work!

I merged it into master, re-run `make build` to update `store-*` files.

There are two issues are think worth solving:

 * I don't like the name of `src/js/platforms/plugin-bridge.js` and `src/js/platforms/plugin-adapter.js` files. What would you think about `inappbilling-bridge.js` and `inappbilling-adapter.js`?

 * Would be nice to have a build system that runs on windows and generates the `www/store-windows.js` files the same way as the Makefile does. Maybe we should put together a simple cross-platform `build.js`? If not we will have very long diff each time some changes are done from windows then from unix, or from unix then from windows.

I made you contributor to the repo and promoted you as the official maintainer of the windows version, if you accept the responsibility? ;-)

**Comment by dkarzon** [comment]
@j3k0 haha yeh I didn't like that naming either but my original name for them was `androidwindows-*` which is even worse. That sounds like a better option. I was also wondering about the `store.plugin` variable, is there any reason that was platform specific (`store.android`)? Or could we apply the same standard to the iOS portion? 

I was playing around with the makefile to try and get it to run on windows, had a path separator variable setup with the below which seemed to work.
```
ifeq ($(OS),Windows_NT)
    PATHSEP2=\\
else
    PATHSEP2=/
endif
PATHSEP=$(strip $(PATHSEP2))
```

Then I ran into issues with the testing suite and I didn't want to mess with that too much.

**Comment by dkarzon** [comment]
Also, definitely keen to become a maintainer of the windows version. Doing a fair bit of work around cordova and windows apps at the moment so I'm sure I'll be adding more. Possibly event some Windows10 support soon.

**Comment by j3k0** [comment]
Excellent!

Yes, the Makefile is full of pipes and other unixness.

`store.android` was a way to allow a developer to eventually tap directly into the low-level android API. As the plugin's high-level API aims to be universal, it's kind of a smallest common denominator, so I was thinking to add official "backdoors" to the lower level APIs, to allow exposing platform specific APIs.

I don't know if anyone is making use of that, but in order not to break their app I'd be willing to keep `store.android` (eventually side by side with `store.inappbilling`). Solved by 7035933

**Pull request merged**
