### PR TITLE
[iOS] - Fix problem on unfinished transaction

### PR DESCRIPTION
**Pull request by atorgfr**
Fix the issue #612

### CODE REVIEW

**Comment by j3k0** [comment]
Hello @atorgfr, this is a bad thing to do. Unfinished transactions are unfinished because they haven't been processed successfully. People might have paid for something and didn't get the stuff. Here you cleanup pending transaction without caring if the products have been delivered (which happens when `product.finish()` is called by the application.

Maybe in development, you sometime need to cleanup pending transactions (that stayed around due to bugs, changes in product ids, whatever...) I added a way to achieve that with commit a8aff06

**Comment by atorgfr** [comment]
Hello @j3k0 I'm OK with you but if there is a problem during validation server side. 
The user is stuck in an infinite loop and can't buy any consumable product. 
I think we can found a better way, but couldn't seen one for the moment. 
Did you look at my issue ?

**Comment by j3k0** [comment]
Hello @atorgfr,

Logically you'd only deliver the consumable after the receipt has been validated. If you do receipt validation, it's to protect yourself against all sort of hacks.

If your validation server is down, you should not deliver and finish the transaction. Eventually, your validation server should get back up and valid purchases will be delivered. Otherwise, it means malicious user can just turn on airplane mode (or block your server) to get their fake purchases approved.

The only case where a purchase will be stuck in the queue forever is for invalid receipts, you shouldn't care about users that tries to hack your in-app-purchases.

If you really wan't to make the choice of letting purchases pass through when receipt validation server isn't reachable, you can do a health check in your `store.validator` function before the actual validation request. No reply to health check => approve the transaction.

__Shameless plug__: you can also use our service https://billing.fovea.cc to validate receipts. It's monitored 24/7, redondant, handles edge cases and is protected for DoS attacks. While nothing can be 100% certain, we put a lot of effort so that it's pretty much always up and running. Oh, and it's free while in beta. But it might become a way for you to support the free work I put on this plugin (if you feel like it). Just saying.

**Comment by jackdyson31** [comment]
@j3k0 : unfortunately it happens even when not using verification via receipts - just my two cents.

**Comment by CoDanny** [comment]
The actual problem here is that the consumable can enter this state for whatever reason (e.g. fails to verify the ticket or fails to deliver the consumable ) even in production. After the product is in this state, there are no events fired... so it's impossible to then call finish on it, thus never exiting this state.

I would recommend that the event "approved" is deliver when the consumable is not finished. At least then, we have a chance to finish it.

**Comment by j3k0** [comment]
There are only 3 cases in which consumable to stay between the `approved` and `finished` state:

1. you are NOT using receipt validation
   - case A: the delivery of products failed. Then it's the app's internal affair to manage those cases and retry until it works...
   - case B: `finished` failed? Apple defines no error case... nor triggers any events. I assume they just retry until it succeeds.
1. you are using receipt validation
   - case C: `validation` failed. The plugin will retry 3 times, then trigger the `unverified` on the product.

Anyway, `approved` should be retriggered next time the app starts, or when the user hits `restore purchases`. Isn't it?

**Comment by CoDanny** [comment]
My concern is 1.A . It's possible that at any point I'm unable to deliver the item and I can't call finish (since nothing has been delivered).

In this case, even I later deliver the item, next item I try to purchase the same consumable, it comes up with the "You have already purchased..." dialog but no event is ever triggered.

In my code, I only listen to the approved callback before I call order, after calling finish or failing I remove the listener. So I won't get any call when the app restarts.

**Comment by j3k0** [comment]
Hi. This is a bug in your code: you have to listen to events as soon as the
app starts. This is not recommended, but required by both Apple and Google.
Tons of reasons can make a purchase flow being interrupted, at any point.
You need to be ready to complete them when app restart. Asking the user to
repurchase is against Apple and Google guidelines: the plugin provides a
"canPurchase" that you should handle to prevent users to click purchase
while a purchase is in-progress. Please read Apple and Google docs about
the subject.

**Comment by CoDanny** [comment]
@j3k0. I have read the guidelines and my app follows them (perhaps in a way that's not compatible with the plugin's current implementation). What I'm asking is something that I believe can be done using the Apple defined APIs and events. Also keep in mind that I'm talking about **consumable purchases**, which can be purchased many times.

What I'm looking for is another "approved" triggered when I call "order" in a consumable that was already purchased but never "finished"

**Comment by j3k0** [comment]
Ref https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/DeliverProduct.html#//apple_ref/doc/uid/TP40008267-CH5-SW4

> Register a transaction queue observer when your app is launched, as shown in Listing 5-1. Make sure that the observer is ready to handle a transaction at any time, not just after you add a transaction to the queue. For example, consider the case of a user buying something in your app right before going into a tunnel. Your app isn’t able to deliver the purchased content because there’s no network connection. The next time your app is launched, StoreKit calls your transaction queue observer again and delivers the purchased content at that time. Similarly, if your app fails to mark a transaction as finished, StoreKit calls the observer every time your app is launched until the transaction is properly finished.

**Comment by CoDanny** [comment]
Thanks @j3k0! Sorry for the trouble. I think I need to do a major re-design of the app

**Comment by jackdyson31** [comment]
Although the discussion is focused upon an Apple implementation (I think), I can't get the consumables to work with Android (I don't use receipts)). The purchase and then lock ownership and there is nothing that I seem to be able to do in the present API. I suspect that the reason for that is the Google methodology requires a "consume" command sent to their server once a consumable (their "managed" class) is purchased.

I use the simplest recommended implementation of the API described in the documentation - it doesn't work on Android (it does on Apple) and I think it could be because of this reason.

We may need an explicit action to consume the purchase I surmise:

https://developer.android.com/google/play/billing/api.html

"To retrieve the list of product's owned by the user, your application sends a getPurchases call to Google Play. Your application can make a consumption request by sending a consumePurchase call. In the request argument, you must specify the in-app product's unique purchaseToken String that you obtained from Google Play when it was purchased. Google Play returns a status code indicating if the consumption was recorded successfully." 

We need to have clear access to the underlying Google API from the plugin maybe?

**Comment by CoDanny** [comment]
@j3k0 I rearchitected my app and now I'm listening for all events all the time. It appears that the approved events do fire but the "additionalData" in my purchase is null... This makes it impossible for me to know how to deliver my consumable and therefore I still can't call finish.

**Comment by garyganyang** [comment]
this discussion is very useful

**Pull request closed without merging**
