### PR TITLE
Changes for durable and consumable purchases on Windows 10.

### PR DESCRIPTION
**Pull request by trumpet2012**
This pull request is in reference to: #456 and #457.

Here are the itemized changes:
 1. The productLicenses were not being loaded from the Windows Store. This was only populated in `setTestMode()` when you were using the sandbox.
 1. The subscribe function was calling `this.buy`, but `this` is the javascript Window object. Calling buy on `this.inappbilling` fixed this. Also passed the productId to the buy function instead of the args list.
 1. `consumePurchase` in InAppPurchaseProxy.js was expecting the list of args to contain the transactionId, however it was not being passed. Now before the transaction is cleared from the product when it reaches the `finished` state the transaction object is stored in a local variable so that its ID can be passed to the consumePurchase call.
 1. The `buy` function was not returning the transaction information that Windows provides. Windows returns a [`PurchaseResults`](https://msdn.microsoft.com/en-us/library/windows/apps/windows.applicationmodel.store.purchaseresults.aspx) object from [`requestProductPurchaseAsync`](https://msdn.microsoft.com/en-us/library/windows/apps/hh779780.aspx). From my logs I could see that Windows returned the object correctly and it contained all of the information that we needed. However, when these results are passed to the success callback the information is lost. My thinking is that somewhere in the process (probably in cordova.exec) the Windows Runtime object is converted to a normal javascript object and it is unable to determine the attributes that should be used. To test this I converted the `PurchaseResults` object that windows gives us to a JSON string using the JSON.stringify method and it simply returned an empty dictionary.

So far I have been able to successfully place a couple of durable products on a Windows 10 application. I am waiting on the Windows store to update with my new Consumable products so that I can test them as well. I have not tested these changes with Windows 8.1. 

This is not ready to merge yet, but I wanted to see what your guys initial thoughts were.

### CODE REVIEW

**Comment by trumpet2012** [comment]
I have tested more durable products on Windows 10 and haven't had any issues. I have also tested a consumable purchase and it was also successful. I'm still waiting for more consumables to get certified in the Windows store, but both consumables and durables are working for me.

**Comment by trumpet2012** [comment]
I have tested this using more consumables and durables and I haven't had any issues.

**Comment by j3k0** [comment]
Hey @trumpet2012,

Thanks for the PR. You said "not ready to merge yet", is this still true? and/or what is left?

If anyone test this PR on his app with either windows 8.1, windows 10 or android let us know if that work or doesn't (because source code is shared between windows and android).

If we get no feedback, I've got no problems merging experimental stuff in the master branch. Adventurous people that don't use one of the stable "tagged" releases will let us know if that create issues with other platforms...

**Comment by trumpet2012** [comment]
Yeah this should be ready to merge. It will be good for other people on other platforms to test it.

**Comment by j3k0** [comment]
@trumpet2012 merged in.

Maybe there are a few things to add/edit to doc/windows.md (that may be different for setup in windows 10 than it was with windows 8.1?)

**Pull request merged**
