### PR TITLE
report Adapter errors to the store

### PR DESCRIPTION
**Pull request by kasparsj**
tested on ios 16 / iphone8

Changes proposed in this pull request:

- report Adapter errors to the store

---

To test this pull request with cordova:

```
# 1: Uninstall the plugin (if already installed)
cordova plugin rm cordova-plugin-purchase

# 2: Install from github
cordova plugin add "https://github.com/j3k0/cordova-plugin-purchase.git#BRANCH_NAME_HERE"
```

### CODE REVIEW

**Comment by kasparsj** [comment]
Hello @j3k0  & thanks for the reviews and merging.
You are writing in the comments that PAYMENT_CANCELLED is not an error in version 13.
In my app I'm showing a loading indicator when clicking on the BUY button, but how can I remove it (when payment cancelled), since the PAYMENT_CANCELLED is not reported by the plugin?

**Comment by j3k0** [comment]
Hey @kasparsj -

Here is how it's done in my test app (where showing "Processing..." is like showing the loading indicator):

```ts
if (isApproved(subscriptions) || isInitiated(subscriptions))
    statusElement.innerHTML = 'Processing...';
  else
    statusElement.innerHTML = '';
}

// Returns true if one of the given product has a transaction in the APPROVED state
function isApproved(products: CdvPurchase.Product[]) {
  return !!findLocalTransaction(products, t => t.state === CdvPurchase.TransactionState.APPROVED);
}

// Returns true if one of the given product has a transaction in the INITIATED state
function isInitiated(products: CdvPurchase.Product[]) {
  return !!findLocalTransaction(products, t => t.state === CdvPurchase.TransactionState.INITIATED);
}

// Find a local transaction for one of the provided products that passes the given filter.
function findLocalTransaction(products: CdvPurchase.Product[], filter: (transaction: CdvPurchase.Transaction) => boolean): CdvPurchase.Transaction | undefined {
  for (const product of products) {
    const transaction = CdvPurchase.store.findInLocalReceipts(product);
    if (!transaction) continue;
    if (filter(transaction)) return transaction;
  }
}
```

**Comment by vogloblinsky** [comment]
@j3k0 I am in the same situation as @kasparsj 
I am changing a button to "Buying..." and i need an event to handle the use-case where the user close the purchase popup.
You solution seems not to be async.

**Comment by j3k0** [comment]
@vogloblinsky This solution is async. The above code is called from a callback that runs on receipt updates: `store.when().receiptUpdated(callback)`.

**Comment by vogloblinsky** [comment]
Ok may be i need to create a new issue ?
My problem is the same as @kasparsj. I cannot catch a cancel event from a user during a purchase process.

**Pull request closed without merging**
