### PR TITLE
[Windows] Fix for loading non-consumable purchases

### PR DESCRIPTION
**Pull request by dkarzon**
Separated out the iabGetPurchases function for Android and Windows to load the windows products in properly.
Also a few docs updates.

This is for Issue #294

### CODE REVIEW

**Comment by j3k0** [comment]
Will merge that, if you can fix the below.

Platform specific logic `store.inappbilling.setTestMode` shouldn't be a public API call. The philosophy of the cordova plugin is to provide a single unified API for all platforms. I'd rather add a `store.sandbox` boolean, that can be ignored by all platform but windows, that is read at initialization. Seems feasible?

**Comment by dkarzon** [comment]
@j3k0 Yep understandable, I'll give it a go.

**Comment by dkarzon** [comment]
@j3k0 Not too sure I like this fix as it means we have to make a platform specific `InAppBilling.prototype.init` because of the way the native android part handles skus as a list instead of an object.
We will probably need to update `InAppBillingPlugin.java` in this case unless you know of a better way to do this?

**Comment by dkarzon** [comment]
@j3k0 I've forked that change off this PR because I don't like it, affects the android version a little too much. So I'd prefer to keep the setTestMode() function for now and get the windows version working with Non-Consumables then we can work on the `store.sandbox` approach.

Thoughts?

**Comment by dkarzon** [comment]
@j3k0 Any chance we can get this merged in so non-consumables aren't broken on for windows?

**Comment by j3k0** [comment]
Hi, yes I can get this merged. But still don't want public platform specific API, that's just the philosophy of this unified plugin. Once people start using platform specific APIs, we're stuck with them.

Having the "setTestMode".

```js
store.sandbox = isMyAppInDebug();
[...]
store.refresh();
```

That works for all platforms. People don't have to learn multiple APIs, this above is coherent with how you set options so far (like `verbosity` and `validator`).

If we start to expose platform specific APIs, wait some time and client-side code will start to look like this:

```js
if (isMyAppInDebug() && isMyAppRunningOnWindows())
    store.inappbilling.setTestMode();

if (isMyAppInDebug() && isMyAppRunningOnIOS())
    store.storekit.setSandbox(true);

if (isMyAppInDebug() && isMyAppRunningOnFirefoxOS())
    store.firefoxbilling.enableTesting = true;

[...]
store.refresh();
```

If I had time I'd do the change, but that won't be for today...

**Comment by dkarzon** [comment]
Do you just want me to move it to `store.setTestMode()`?
None of the other platforms have a test/sandbox mode implemented yet do they?

**Comment by dkarzon** [comment]
@j3k0 I've fixed this up so the windows setTestMode function is gone and now uses a `store.sandbox` property to set it to use the simulator.

**Pull request merged**
