### PR TITLE
Fix price for winphone and unhandled cancel of purchase from initiated state

### PR DESCRIPTION
**Pull request by ArenSH**
Fix title and price according to [ProductListing class](https://msdn.microsoft.com/en-US/library/windows/apps/windows.applicationmodel.store.productlisting.aspx)

Also add minor fix to properly trigger "cancelled" event when purchase cancelled from initiated state

### CODE REVIEW

**Comment by j3k0** [comment]
Hey @ArenSH 

Changes to JS files needs to be done in the `src/js` folder. The files located in `www/` are generated at build time, your changes to `www/store-windows.js` will be lost when someone builds a new release of the plugin.

**Comment by j3k0** [comment]
@dkarzon would you like to take a look?

**Comment by ArenSH** [comment]
Sorry for not replied earlier,
I fixed source files and rebuild www/* files.

**Comment by j3k0** [comment]
Thanks for the contribution!

**Pull request merged**
