### PR TITLE
Added price_amount_micros to product data

### PR DESCRIPTION
**Pull request by tehmaestro**
Might be useful for others, me included. Reference in Table 2 https://developer.android.com/google/play/billing/billing_reference.html

### CODE REVIEW

**Comment by j3k0** [comment]
Can you indicate in the documentation in `product.js` that the value is only defined on Android. After that, it looks ok to merge! 👍

**Comment by j3k0** [comment]
@tehmaestro Any reasons you have closed this PR?

**Comment by tehmaestro** [comment]
Yeah, sorry, I screwed up something with my commits, I added more than I wanted too, I will redo or reopen the pull request. Sorry.

**Comment by j3k0** [comment]
No problems, I wanted to check if this was by mistake.

**Comment by tehmaestro** [comment]
Recreated: https://github.com/j3k0/cordova-plugin-purchase/pull/531

**Pull request closed without merging**
