### PR TITLE
Add developerPayload option.

### PR DESCRIPTION
**Pull request by agamemnus**
http://stackoverflow.com/questions/27761553/google-play-in-app-billing-in-app-purchases-purchase-verification-and-consu

Just run it like this:
`store.order (product, payloadString)`

Developer payloads can't really be secured from tampering within the app. You would need to check their validity within an server.

### CODE REVIEW

**Comment by CodeHunger** [comment]
You may not be the right person to ask this question but i'll ask it any way.
Is it also possible to set a developerPayload in ios?
I know that your vork only supports android.
But i'm wondering if it is even possible with ios iap.

**Comment by agamemnus** [comment]
Sorry, I have no idea at the moment...

**Comment by j3k0** [comment]
Hey @agamemnus -- I know this pull request has been around for a while, sorry bout that.

Do you remember what happens with your code if someone doesn't want to use the payload?

**Comment by agamemnus** [comment]
Sure, np. In regards to your question, note that your code has developer
payload set to "", and I use undefined by default. That might have to be
checked for and changed to a "" string when sending to the Java function. I
am not sure if that was an oversight on my part.

**Pull request closed without merging**
