### PR TITLE
Windows support

### PR DESCRIPTION
**Pull request by phfsantos**

### CODE REVIEW

**Comment by j3k0** [comment]
Hey @phfsantos 

Seems like there's a lot in common between this and the android version?

Would it be possible to merge things? Also, anything special regarding installation and configuration?

**Comment by phfsantos** [comment]
yeah it can merged with android.I separated them just in case things would change later on. There is nothing special on the configuration for windows. It should work just as the android part.

Date: Wed, 1 Jul 2015 23:25:36 -0700

**Comment by j3k0** [comment]
@dkarzon

**Comment by dkarzon** [comment]
Oh wow I didn't even see this PR. I'll take a look and see if I can help out.

**Comment by j3k0** [comment]
@dkarzon that'd be awesome.

The major issue with this PR is that `windows-*.js` are copy-paste of `android-*.js` (I don't know what really changed). For obvious reasons it shouldn't be that way.

Do no hesitate to ask if you need any help figuring things out.

**Comment by dkarzon** [comment]
@j3k0 I had a crack at it last night and got it mostly working with a merged store-androidwindows.js looks like the main thing that changed was to deal with different json objects coming back from the native components were different and some naming. So have a go at fixing that.

**Pull request merged**
